In [1]:
import numpy as np
arr=np.array([1,2,2,3,4,5,6,7,8,9,77])
print(arr[2:8])

[2 3 4 5 6 7]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[:8])

[1 2 3 4 5 6 7 8]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:])

[3 4 5 6 7 8 9]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:8:3])

[2 5 8]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[:8:3])

[1 4 7]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1::3])

[2 5 8]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[::3])

[1 4 7]


NEGATIVE SLICING

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-1])

9


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-1:-7:3])

[]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-1:7:-3])


[9]


Slicing 2-D Arrays

In [16]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1]])
print(arr[0, 2:8])

[3 4 5 6 7 8]


In [17]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1]])
print(arr[1, 1:9])

[8 7 6 5 4 3 2 1]


In [18]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])


[3 8]


In [19]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1:6, 0:1])

[[6]]


In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:3])

[[2 3]
 [7 8]]
