In [9]:
import numpy as np
arr=np.array([1,1,1,1,1])
print(arr)


[1 1 1 1 1]


In [10]:
import numpy as np
arr=np.array([11, 23,1])
print(arr)



[11 23  1]


In [11]:
import numpy as np
arr=np.array((1,2,3))
print(arr)


[1 2 3]


0-Dimensional Array

In [12]:
import numpy as np
arr = np.array(42)
print(arr)

42


1-Dimensional Array

In [13]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


2-Dimensional Array

In [14]:
import numpy as np
arr=np.array([[1,2,3,4],[2,3,6,7]])
print(arr)

[[1 2 3 4]
 [2 3 6 7]]


3-Dimensional Array

In [15]:
import numpy as np
arr=np.array([[[1,2,3],[9,8,7],[3,5,7]]])
print(arr)


[[[1 2 3]
  [9 8 7]
  [3 5 7]]]


Dimension of an Array(ndim)

In [16]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


Higher Dimensional Arrays

In [17]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [3, 4, 5, 6]], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]
    [3 4 5 6]]]]]
number of dimensions : 5
