Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
Below is a list of all data types in NumPy and the characters used to represent them.
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr = np.array([1.1, 2.0, 3.8, 4.9])
print(arr.dtype)

float64


In [ ]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


Creating Arrays With a Defined Data Type

In [ ]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'], dtype="S")
print(arr)
print(arr.dtype)

[b'apple' b'banana' b'cherry']
|S6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
import numpy as np

arr = np.array([1.1, 2.3, 3.4, 4.7], dtype='f4')

print(arr)
print(arr.dtype)

[1.1 2.3 3.4 4.7]
float32


Converting Data Type on Existing Arrays

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarray= arr.astype("f")
print(newarray, arr.dtype)

[1. 2. 3. 4. 5. 6.] int64


In [6]:
import numpy as np
arr=np.array([1,0,0,0])
newarray= arr.astype("S")
print(newarray, arr.dtype)

[b'1' b'0' b'0' b'0'] int64


In [4]:
import numpy as np
arr=np.array([1.2,3.4,5.6])
newarray= arr.astype("i")
print(newarray, arr.dtype)

[1 3 5] float64
