In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,67,7,8,8,8,8,9])
print(arr)
print()
for i in arr:
    print(i)

[ 1  2  3  4  5  6 67  7  8  8  8  8  9]

1
2
3
4
5
6
67
7
8
8
8
8
9


In [2]:
import numpy as np
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(a)
print()
for j in a:
    print(j)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
import numpy as np
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(a)
print()
for j in a:
    print(j)
    for k in a:
     for l in k:
       print(l)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [9]:
import numpy as np
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(a)
print()
for i in np.nditer(a):
    print(i)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

1
2
3
4
1
2
3
4
1
2
3
4


In [13]:
import numpy as np
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(a)
print()
for j in a:
    print(j)
    for k in a:
     for l in k:
       print(l)
       for i in np.nditer(l):
            print(i)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
1
2
3
4
[1 2 3 4]
1
2
3
4
[1 2 3 4]
1
2
3
4


In [14]:
import numpy as np
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i,d in np.ndenumerate(a):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,67,7,8,8,8,8,9])
print(arr)
print()
for i,d in np.ndenumerate(arr):
    print(i,d)

[ 1  2  3  4  5  6 67  7  8  8  8  8  9]

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 67
(7,) 7
(8,) 8
(9,) 8
(10,) 8
(11,) 8
(12,) 9
