Reshaping arrays
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape From 1-D to 2-D

In [3]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,15])
newarr= arr.reshape(3,5)
print(newarr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
import numpy as np
arr=np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16]])
newarr= arr.reshape(1, 16)
print(newarr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [10]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
newarr= arr.reshape(8, 2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


Reshape From 1-D to 3-D

In [15]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
newarr= arr.reshape(2, 2,4)
print(newarr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [16]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
newarr= arr.reshape(1, 4,4)
print(newarr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]


In [17]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
newarr= arr.reshape(1, 1,16)
print(newarr)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Returns Copy or View?

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)



[1 2 3 4 5 6 7 8]


Unknown Dimension

In [31]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening the arrays

In [32]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [33]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6], [5, 8, 9]]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 5 8 9]
