The copy is a new array,
The view is just a view of the original array.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=42
print(arr)
print(x)


[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
y=arr.view()
arr[0]=42
print(arr)
print(x)
print(y)

[42  2  3  4  5  6]
[1 2 3 4 5 6]
[42  2  3  4  5  6]
