The copy is a new array,
The view is just a view of the original array.

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=42
print(arr)
print(x)


[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
y=arr.view()
arr[0]=42
print(arr)
print(x)
print(y)

[42  2  3  4  5  6]
[1 2 3 4 5 6]
[42  2  3  4  5  6]


Check if Array Owns its Data

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[1]=45
print(x.base)
print(y.base)

None
[ 1 45  3  4  5]


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[1]=45
print(x)
print(y.base)

[1 2 3 4 5]
[ 1 45  3  4  5]
